version: "3.3"

services: 
  web:
    build: ./server
    ports: 
      - ${LOCAL_SERVER_PORT}:${DOCKER_SERVER_PORT}

  db:
    build: ./db
    ports: 
      - ${LOCAL_DB_PORT}:${DOCKER_DB_PORT}
    volumes: 
      - ./testdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}

  adminer:    
    image: adminer    
    restart: always    
    ports:      
      - 8080:8080
