version: "3.8"

services: 
  web:
    build: .
    ports: 
      - "3000:3000"
    volumes: 
      - .:/products-api

  db:
    build: ./db
    ports: 
      - "5432:5432"
    volumes: 
      - ./testdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
