version: "3.3"

services: 
  web:
    build: .
    ports: 
      - ${LOCAL_SERVER_PORT}:${DOCKER_SERVER_PORT}
    environment:
      PGHOST: ${POSTGRES_HOST}
      PGPORT: ${DOCKER_DB_PORT}
      PGUSER: ${POSTGRES_USER}
      PGDATABASE: ${POSTGRES_DB}
      PGPASSWORD: ${POSTGRES_PASS}
      
      
    